server:
  port: 53024
  servlet:
    context-path: /cart
spring:
  application:
    name: cart-service
  freemarker:
    charset: UTF-8
    content-type: text/html
    enabled: true
    request-context-attribute: rc
    suffix: .html
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false
  cloud:
    alibaba:
      seata:
        # 自定义事务组名称需要与seata-server中的对应
        tx-service-group: fsp_tx_group
    nacos:
      discovery:
        server-addr: 192.168.87.101:3333,192.168.87.101:4444,192.168.87.101:5555 #配置Nacos地址
    sentinel:
      eager: true
      transport:
        # 配置Sentinel dashboard地址
        dashboard: localhost:8080
        # 默认8719端口，假如被占用会自动从8719开始一次+1扫描，直至找到被占用的端口。
        port: 8719
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.87.101:3306/area_cart?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 3333


#seata:
#  tx-service-group: fsp_tx_group
#  config:
#    type: nacos
#    nacos:
#      namespace:
#      serverAddr: 192.168.43.64:3333
#      group: DEFAULT_GROUP
#      username: ""
#      password: ""
#  registry:
#    type: nacos
#    nacos:
#      server-addr: 192.168.43.64:3333
#      group: DEFAULT_GROUP
#      namespace:
#      username: nacos
#      password: nacos
#      application: seata-server

feign:
  compression:
    request:
      enabled: true
      mime-types:
        - text/xml
        - application/xml
        - application/json
      min-request-size: 2048
    response:
      enabled: true
  hystrix:
    enabled: true
logging:
  level:
    org:
      springframework:
        web: info
    root: debug
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,env

#数据库
mybatis-plus:
  mapper-locations: classpath:com/zjazn/cart/mapper/xml/*.xml
  #日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
