server:
  port: 53010
spring:
  application:
    name: gateway-server
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.87.101:3333,192.168.87.101:4444,192.168.87.101:5555 # 配置nacos注册中心地址
    gateway:

      # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      discovery:
        locator:
          enabled: true
      routes:
        # 路由 1
        - id: user-service #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:53021   #匹配后提供服务的路由地址
          uri: lb://user-service
          predicates:
            - Path=/user/**   #断言,路径相匹配的进行路由
        # 路由 2
        - id: uaa-service
          #uri: http://localhost:53020
          uri: lb://uaa-service
          predicates:
            - Path=/uaa/**   #断言,路径相匹配的进行路由
        # 路由 3
        - id: product-service
          #uri: http://localhost:53020
          uri: lb://product-service
          predicates:
            - Path=/product/**   #断言,路径相匹配的进行路由
        # 路由 4
        - id: store-service
          #uri: http://localhost:53020
          uri: lb://store-service
          predicates:
            - Path=/store/**   #断言,路径相匹配的进行路由
        # 路由 4
        - id: store-service
          #uri: http://localhost:53020
          uri: lb://cart-service
          predicates:
            - Path=/cart/**   #断言,路径相匹配的进行路由
            #- After=2020-21-01T06:06:06+08:00[Asia/Shanghai]
            #- Between=2020-12-01T06:06:06+08:00[Asia/Shanghai], 2020-12-16T06:06:06+08:00[Asia/Shanghai]
            #- Cookie=token, \d+
            #- Header=token, \d+
            #- Host=**.baidu.com,**.zjazn.com
            #- Method=GET,POST
            #- Query=token,\d+
            #- Weight=group1,95

feign:
  compression:
    request:
      enabled: true
      mime-types:
        - text/xml
        - application/xml
        - application/json
      min-request-size: 2048
    response:
      enabled: true
  hystrix:
    enabled: true
logging:
  level:
    org:
      springframework: info
    root: info
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,env





